# Generated by Django 5.1.4 on 2024-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paintai", "0005_productproduction_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
